name: "nix"
on:
  pull_request:
  push:
jobs:
  nix-build:
    name: "build"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix build
  nix-flake-check:
    runs-on: ubuntu-latest
    name: "check"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    - run: nix flake check --impure
  nixfmt:
    runs-on: ubuntu-latest
    name: "fmt"
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v20
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
        nix_path: nixpkgs=channel:nixos-unstable
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - name: "treefmt"
      run: nix develop .#fmtShell --command treefmt --fail-on-change
