name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
    #- name: Print nixpkgs version
      #run: nix-instantiate --eval -E '(import <nixpkgs> {}).lib.version'
    - run: nix build
    - run: nix flake check --impure
